### ISSUE TITLE
Complete account profiles

### ISSUE THREAD

**Issue by techtolentino** [collectivfam/hello_mars_ep#14]
Each platform account should have a complete profile

- [ ] [Twitter](https://twitter.com/collectivfam)
- [ ] [Instagram](https://www.instagram.com/collectivfam/)
- [ ] [SoundCloud](http://soundcloud.com/collectivfam)
- [ ] [GitHub](https://github.com/collectivfam)
- [ ] [Medium](https://medium.com/@collectivfam)
- [ ] [Slack](https://collectivfam.slack.com/)
- [ ] Site's About Us

**Comment by collectivfam** [comment]
*Note* - had to switch usernames from `thecollectivelegacy` everywhere, to `collectivfam`, since Twitter capped at 15 chars
